# Generated by Django 3.2.3 on 2021-06-01 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20210601_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 16, 11, 49, 1, 345627), unique=True),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 1, 11, 49, 1, 345594), unique=True),
        ),
    ]
