# Generated by Django 3.2.3 on 2021-06-01 11:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20210601_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 16, 11, 50, 40, 394060, tzinfo=utc), unique=True),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 1, 11, 50, 40, 394030, tzinfo=utc), unique=True),
        ),
    ]
