# Generated by Django 3.2.3 on 2021-06-01 11:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20210601_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='end_date',
            field=models.DateField(blank=True, default='', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, unique=True),
        ),
    ]
